// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/WildEgor/gImageResizer/internal/adapters"
	"github.com/WildEgor/gImageResizer/internal/configs"
	"github.com/WildEgor/gImageResizer/internal/handlers/http"
	"github.com/WildEgor/gImageResizer/internal/routers"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from server.go:

func NewServer() (*fiber.App, error) {
	appConfig := configs.NewAppConfig()
	s3Config := configs.NewS3Config()
	s3Adapter := adapters.NewS3Adapter(s3Config)
	saveFilesHandler := handlers.NewSaveFilesHandler(appConfig, s3Adapter)
	imgProxyConfig := configs.NewImgProxyConfig()
	downloadFileHandler := handlers.NewDownloadFileHandler(imgProxyConfig, appConfig, s3Adapter)
	httpRouter := routers.NewHTTPRouter(saveFilesHandler, downloadFileHandler)
	app := NewApp(appConfig, httpRouter)
	return app, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
