// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/WildEgor/gImageResizer/internal/configs"
	"github.com/WildEgor/gImageResizer/internal/routers"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from server.go:

func NewServer() (*fiber.App, error) {
	appConfig := configs.NewAppConfig()
	httpRouter := routers.NewHTTPRouter()
	app := NewApp(appConfig, httpRouter)
	return app, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
